services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ensek-sqlserver
    environment:
      SA_PASSWORD: "No+S0S3curePwd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql

  api:
    build:
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: ensek-meter-api
    depends_on:
      - db
    environment:
      ConnectionStrings__EnsekDbContext: "Server=db;Database=EnsekDb;User Id=sa;Password=No+S0S3curePwd!;Encrypt=True;TrustServerCertificate=True;"
    ports: ["5000:8080"]
    
volumes:
  db-data:
